# Generated by Django 2.0.7 on 2018-07-30 02:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('days', models.IntegerField(default=3)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
