# Generated by Django 2.0.7 on 2018-07-30 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Tasks',
        ),
    ]
